### ISSUE TITLE
upgrade usage of TryGhost/action-deploy-theme from 1.0.0 which has broken

### ISSUE THREAD

**Issue by james-baker** [TryGhost/Lyra#74]
Forked this repo today, and the deploy workflow is broken.

Error from the GitHub action runner output:
```
Run TryGhost/action-deploy-theme@v1.0.0
  with:
    api-url: ***
    api-key: ***
(node:2779) UnhandledPromiseRejectionWarning: Error: GhostAdminAPI Config Invalid: @tryghost/admin-api requires a "key" in following format {A}:{B}, where A is 24 hex characters and B is 64 hex characters
    at GhostAdminAPI (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:6642:15)
    at new GhostAdminAPI (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:6588:16)
    at main (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:1207:17)
    at Object.104 (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:1231:2)
    at __webpack_require__ (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:37:19)
    at /home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.0.0/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

Upgrading to TryGhost/action-deploy-theme@v1.3.1 worked fine for me.
Or, I see that https://github.com/TryGhost/Starter/blob/master/.github/workflows/deploy-theme.yml uses TryGhost/action-deploy-theme@v1.2.0 , probably just staying in sync with upstream would be simpler

**Comment by daniellockyer** [comment]
The Action has been updated to 1.4.0 :slightly_smiling_face:
